#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# FZF configuration
source <(fzf --zsh)
# Open in tmux popup if on tmux, otherwise use --height mode
export FZF_DEFAULT_OPTS="--height 40% --tmux bottom,40% --layout reverse --border top --bind 'shift-up:preview-up,shift-down:preview-down'"
# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
# Print tree structure in the preview window
export FZF_ALT_C_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'tree -C {}'"

source $HOME/.fzf-git.sh/fzf-git.sh

if [[ -s "$HOME/dotfiles/.secrets" ]]; then
   source "$HOME/dotfiles/.secrets"
fi

# Starship prompt
eval "$(starship init zsh)"

# Homebrew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# direnv
eval "$(direnv hook zsh)"

# opencode
export PATH=/home/cezar/.opencode/bin:$PATH

# bun completions
[ -s "/home/cezar/.bun/_bun" ] && source "/home/cezar/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

alias emacs="emacs -nw"
